CELEBRITIES = [
    "Brad Pitt", "Scarlett Johansson",
    "Ryan Gosling", "Jennifer Lawrence", "Tom Cruise", "Angelina Jolie", "Chris Evans",
    "Leonardo DiCaprio", "Margot Robbie", "Chris Hemsworth", "Natalie Portman", "Will Smith",
    "Emma Stone", "Robert Downey Jr.", "Zendaya", "Tom Hanks", "Anne Hathaway",
    "Dwayne Johnson", "Gal Gadot", "Johnny Depp", "Mila Kunis", "Keanu Reeves",
    "Charlize Theron", "Mark Wahlberg", "Megan Fox", "Ryan Reynolds", "Blake Lively",
    "Chris Pratt", "Jennifer Aniston", "Hugh Jackman", "Halle Berry", "Matt Damon",
    "Sandra Bullock", "Ben Affleck", "Julia Roberts", "George Clooney", "Cameron Diaz",
    "Bradley Cooper", "Salma Hayek", "Channing Tatum", "Jessica Alba", "Zac Efron",
    "Kate Winslet", "Tom Hiddleston", "Emma Watson", "Daniel Radcliffe", "Rachel McAdams",
    "Jake Gyllenhaal", "Nicole Kidman", "Matthew McConaughey", "Meryl Streep", "Morgan Freeman",
    "Harrison Ford", "Samuel L. Jackson", "Denzel Washington", "Bruce Willis", "Sylvester Stallone",
    "Arnold Schwarzenegger", "Clint Eastwood", "Al Pacino", "Robert De Niro", "Jack Nicholson",
    "Anthony Hopkins", "Christian Bale", "Heath Ledger", "Jared Leto", "Joaquin Phoenix",
    "Jim Carrey", "Adam Sandler", "Will Ferrell", "Steve Carell", "Kevin Hart",
    "Seth Rogen", "Jonah Hill", "Paul Rudd", "Jason Bateman", "Jason Sudeikis",
    "Bill Murray", "Eddie Murphy", "Martin Lawrence", "Chris Tucker", "Jackie Chan",
    "Jet Li", "Bruce Lee", "Keira Knightley", "Orlando Bloom", "Elijah Wood",
    "Viggo Mortensen", "Ian McKellen", "Patrick Stewart", "Hugh Grant", "Colin Firth",
    "Daniel Craig", "Pierce Brosnan", "Sean Connery", "Tom Hardy", "Cillian Murphy",
    "Michael Fassbender", "James McAvoy", "Henry Cavill", "Benicio del Toro", "Javier Bardem",
    "Penelope Cruz", "Antonio Banderas", "Rihanna", "Beyonce", "Taylor Swift",
    "Katy Perry", "Lady Gaga", "Ariana Grande", "Selena Gomez", "Justin Bieber",
    "Ed Sheeran", "Bruno Mars", "The Weeknd", "Drake", "Eminem",
    "Kanye West", "Jay-Z", "Snoop Dogg", "Post Malone", "Shawn Mendes",
    "Billie Eilish", "Dua Lipa", "Miley Cyrus", "Demi Lovato", "Nicki Minaj",
    "Cardi B", "Megan Thee Stallion", "Doja Cat", "Olivia Rodrigo", "Harry Styles",
    "Zayn Malik", "Niall Horan", "Liam Payne", "Louis Tomlinson", "Charlie Puth",
    "Sam Smith", "Adele", "Celine Dion", "Mariah Carey", "Whitney Houston",
    "Michael Jackson", "Prince", "David Bowie", "Freddie Mercury", "Elton John",
    "Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr", "Mick Jagger",
    "Keith Richards", "Steven Tyler", "Axl Rose", "Slash", "Kurt Cobain",
    "Dave Grohl", "Chris Cornell", "Eddie Vedder", "Anthony Kiedis", "Flea",
    "Bono", "The Edge", "Bruce Springsteen", "Bob Dylan", "Neil Young",
    "Tom Petty", "Johnny Cash", "Willie Nelson", "Dolly Parton", "Shania Twain",
    "Garth Brooks", "Tim McGraw", "Faith Hill", "Carrie Underwood", "Miranda Lambert",
    "Blake Shelton", "Luke Bryan", "Jason Aldean", "Eric Church", "Chris Stapleton",
    "Lionel Messi", "Cristiano Ronaldo", "Neymar", "Kylian Mbappe", "Erling Haaland",
    "LeBron James", "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo", "Luka Doncic",
    "Tiger Woods", "Phil Mickelson", "Rory McIlroy", "Dustin Johnson", "Brooks Koepka",
    "Tom Brady", "Patrick Mahomes", "Aaron Rodgers", "Drew Brees", "Peyton Manning"
]
